### ISSUE TITLE
Milestone 2 final check

### ISSUE THREAD

**Issue by MartinStyk** [MartinStyk/pa165-activity-tracker#18]
*Project Requirements:*
_Implement Facade layer interfaces and implementations._
- [x] Everything that should happen in the system must be available through these interfaces (create entities, deleting them etc);
- [x] You must have at least 2 non-trivial business functions on Service Layer (the example project contains several of them). Service layer is not always just a place to delegate to DAO;

_Other points about the Facade and Service layers:_
- [x] All the classes must be wired via dependency injection. Your service objects should obtain an instance of the EntityManager that way;
- [x] All the facade interfaces must not reference entities, but Transfer Objects only;
- [x] All service interfaces must reference only entities, not Data Transfer Objects;
- [x] You can use Dozer framework to map entity instances to transfer objects. The mapping may be done on Facade Layer;
- [x] Facade layer is used to drive transactions;
- [x] Change layout of your project to Multimodule Maven project (tutorial here http://maven.apache.org/guides/getting-started/index.html) Your project should have 3 separate modules:
   *   DAO layer
   *   Service Layer and Facade Layer implementation
   *   API layer - just DTOs and facade interfaces!
- [x] Facade layer will use Service layer and Service layer will use DAO layer;
- [x] Make sure that DataAccessException or its subclass is thrown in case of any exception on a the DAO layer;
- [x] Implement simple unit tests for facade layer. Just one simple test per method is enough. This is mainly so that it’s easy to verify the Facade layer works;
- [x] There must be extensive unit tests for the service layer (particularly for your 2 business functions) and all the tests of service layer must use Mock DAO objects;

_Evaluation Checklist:_
Maximum number of points for this milestone is 10 points;
* -2 points if it is not possible to compile the project and run tests using “mvn clean install”;
* -2 points if there are test failures;
* minimally -1 point for each of the unmet project requirements;
* - 1 point for each occurrence of a team member not contributing enough;
* If a team member was not contributing at all, or very little, you should explicitly say this in your evaluation report. Tutor will follow up on this information;

**Comment by MartinStyk** [comment]
@adamlaurencik @jangrundmann @Ondrejkova 
Hi, I made a quick check and it looks good to me. It would be great if you could take a look and review code. We should discuss all possible issues here
